spring.application.name=pandemonium-api

server.port=8080

# Configuração do Banco de Dados (que ainda não tão la)
spring.datasource.url=jdbc:mysql://localhost:3306/banco_Pandemonium
spring.datasource.username=seu_usuario
spring.datasource.password=sua_senha
spring.jpa.hibernate.ddl-auto=update
